processor_config:
  stream_subscriber_config:
    grpc_data_service_address: https://grpc.testnet.aptoslabs.com:443
    auth_token: replace_me
  dispatcher_config: {}
  blob_store_config: {}
  common_storage_config:
    initial_starting_version: 774295854
  processor_config:
    question_contract_address: "0x71439c26dac05dd500d74a2b81bf3c1f7a83103536ac5d49f97da6bd1f238684"
storage_config:
  connection_string: "postgres://dport:@127.0.0.1:5432/summits"
