[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
bevy = "0.12.1"
bevy_prototype_lyon = "0.10.0"
clap = "4.4.18"
nannou = { version = "0.19.0", features = ["wasm-experimental"] }
rand = "0.8.5"
