[package]
name = "web"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
# Internal
artcore = { workspace = true }

# External
web-sys = { workspace = true }
wasm-bindgen = { workspace = true }
